M48
; DRILL file {KiCad 7.0.9} date Mon Nov 27 16:58:47 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-27T16:58:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0638
%
G90
G05
T1
X5.7874Y-4.4488
X6.2874Y-4.4488
T2
X5.1575Y-4.3307
X5.1575Y-4.4307
T3
X6.5748Y-4.0039
X6.5748Y-4.189
T0
M30
